## <center>PyTorch Basics Exercises</center>

In [1]:
import numpy as np
import torch

**Set the random seed for NumPy and PyTorch both to "42"**

In [2]:
torch.manual_seed(42)

**Create a tensor "x" from the array above**

In [3]:
x = torch.randint(0, 5, (6, ))
x

tensor([2, 2, 1, 4, 1, 0])

**Reshape x into a 3x2 tensor**

In [4]:
x = x.view(3, 2)
x

tensor([[2, 2],
        [1, 4],
        [1, 0]])

**Return the right-hand column of tensor x**

In [5]:
slice = x[:,1:]
slice


tensor([[2],
        [4],
        [0]])

**Without changing x, return a tensor of square values of x**

In [6]:
squares = x.pow(2)
squares

tensor([[ 4,  4],
        [ 1, 16],
        [ 1,  0]])

**Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x**


In [7]:
y = torch.randint(0, 5, (2, 3))
y

tensor([[0, 4, 0],
        [3, 3, 4]])

**Find the matrix product of x and y**

In [8]:
mat_prod = x.mm(y)
mat_prod

tensor([[ 6, 14,  8],
        [12, 16, 16],
        [ 0,  4,  0]])